name: localize_and_translate
description: Easy Localize and Translate your flutter app, with this easy and powerful plugin
version: 1.0.1+5
homepage: https://github.com/MohamedSayed95/localize_and_translate

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6

flutter:
  plugin:
    androidPackage: net.msayed.localize_and_translate
    pluginClass: LocalizeAndTranslatePlugin
